#!/bin/sh

# Process the command line parameters
USER="`id -un`"
if [ "$1" = "-u" ];then
   USER="$2"
   shift 2
fi
# Test for adequate parameters
if [ $# -lt 3 ]; then
   echo "Usage: $0 [-u userid] course assignment file ..." >&2
   exit 1
fi
COURSE=$1
ASG=$2
shift 2

# Pass the tarball over the "access.cs.clemson.edu" and run a script that
# does the handin. 
tar cf - "$@" | ssh "$USER"@access.cs.clemson.edu "sh -ec ' \
  T=\`mktemp -d\`; \
  cd \$T; \
  submit $COURSE $ASG \`tar xvf -\`; \
  rm -r \$T; \
'"
